[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://samco-5f69.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
